image: maven:3.8-openjdk-17

default:
  tags:
    - localshellrunner

stages:
  - test

tests:
  stage: test
  script:
    - mvn test
  artifacts:
    paths:
      - target/ci-cd-test-0.0.1-SNAPSHOT.jar