image: maven:latest or image: maven:3-jdk-10 or image: maven:3-jdk-9

default:
  tags:
    - shelllocal

stages:
  - test

tests:
  stage: test
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/surefire-reports/*