image: maven:3.8-openjdk-17

default:
  tags:
    - dockerlocalrunner

stages:
  - test
  - build

test:
  stage: test
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/ci-cd-test-0.0.1-SNAPSHOT.jar

build:
  stage: build
  script:
    - java -jar target/ci-cd-test-0.0.1-SNAPSHOT.jar