image: maven:3.8-openjdk-11
build:
  script: "mvn install -B"

default:
  tags:
    - shelllocal

stages:
  - test

tests:
  stage: test
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/surefire-reports/*